#pragma config(Sensor, S3,     lightSensor,         sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


/*--------------------------------------------------------------------------------------------------------*\
|*                                                                                                        *|
|*                                          - Wait for Dark -                                             *|
|*                                            ROBOTC on NXT                                               *|
|*                                                                                                        *|
|*  This program runs your taskbot forward until it detects a dark surface.                               *|
|*                                                                                                        *|
|*                                        ROBOT CONFIGURATION                                             *|
|*    NOTES:                                                                                              *|
|*    1)  The Light Sensor is attached to the back of the robot.                                          *|
|*    2)  Be sure to take readings of your Light Sensor over the light and dark areas.  Once you have     *|
|*        the values, add them and divide by 2 to find your threshold.  Then, use your threshold as a     *|
|*        comparison in your program.                                                                     *|
|*                                                                                                        *|
|*    MOTORS & SENSORS:                                                                                   *|
|*    [I/O Port]              [Name]              [Type]              [Description]                       *|
|*    Port C                  motorC              NXT                 Right motor                         *|
|*    Port B                  motorB              NXT                 Left motor                          *|
|*    Port 1                  lightSensor         Light Sensor        Back mounted                        *|
\*---------------------------------------------------------------------------------------------------4246-*/
int i = 0;

task main()
{
	                         // The program waits 50 milliseconds to initialize the light sensor.
	while(i < 9) {
		wait1Msec(100);
		clearTimer(T1);
		while(SensorValue[lightSensor] > 50)   // While the reading is greater than 50 (a light surface):  NOTE- make this less than to detect light surfaces.
		{
			motor[motorB] = 50;                
			motor[motorC] = 50;                
		}
		
		motor[motorB] = -25;                     // Motor C is stopped with a 0 power level.
		motor[motorC] = -25;                     // Motor B is stopped with a 0 power level.
    wait1Msec((time1(T1)) * 2);
    i++;
    motor[motorB] = 50;                
		motor[motorC] = 50;
		wait1Msec((time1(T1)) * 2);
		i++;
 }
}
